name: Nightly Data File Change

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so quote this string
    - cron:  '0 0 * * *'

jobs:
  # Run the common workflow on each pull request
  Nightly_Data_File_Change:
    uses: 51Degrees/common-ci/.github/workflows/nightly-data-file-change.yml@main
    with:
      repo-name: ${{ github.event.repository.name }}
    secrets: 
      token: ${{ secrets.ACCESS_TOKEN }}
      device-detection-key: ${{ secrets.DEVICE_DETECTION_KEY }}
      device-detection-url: ${{ secrets.DEVICE_DETECTION_URL }}
